
-- ============================================================
-- File Name: control_path.vhd
-- ============================================================
-- ************************************************************
-- THIS IS A AUTO-GENERATED FILE. DO NOT EDIT THIS FILE!
-- 
-- 2.0 BUILD. GENERATED ON 2016-11-22
-- ************************************************************

LIBRARY IEEE;
USE ieee.numeric_std.all;
USE ieee.std_logic_1164.all;

ENTITY control_path IS
	PORT(
		start: IN STD_LOGIC := '0';
		complete: OUT STD_LOGIC := '0';
		clk: IN STD_LOGIC := '0';
		reset: IN STD_LOGIC := '0';
		T: OUT STD_LOGIC_VECTOR( 0 TO 36 ) := (others => '0'));
END ENTITY;

ARCHITECTURE control OF control_path IS
	TYPE fsm_state IS ( init, S0, S1, S2, S3, S4, S5, done );
	SIGNAL nQ, Q: fsm_state := init;

BEGIN
	clock: PROCESS(clk)
	BEGIN
		if(clk'EVENT AND clk = '1') THEN
			Q <= nQ;
		END IF;
	END PROCESS;

	next_state: PROCESS( reset, start, Q )
	begin
		nQ <= Q;
 		IF (reset = '1') THEN
			nQ <= init;
		ELSE
			CASE Q IS
				WHEN init =>
					if (start = '1') then nQ <= S0;
					END IF;
				WHEN S0 => nQ <= S1;
				WHEN S1 => nQ <= S2;
				WHEN S2 => nQ <= S3;
				WHEN S3 => nQ <= S4;
				WHEN S4 => nQ <= S5;
				WHEN S5 => nQ <= done;
				WHEN done => nQ <= init;
				WHEN OTHERS => nQ <= init;
			END CASE;
		END IF;

	END PROCESS;

	T_process: PROCESS ( Q )
	BEGIN
		T <= (OTHERS => '0');
		complete <= '0';
		CASE Q IS
			WHEN init =>
				T(12) <= '1';
				T(13) <= '1';
				T(14) <= '1';
				T(15) <= '1';
			WHEN S0 =>
				T(16) <= '1';
				T(17) <= '1';
				T ( 6 TO 8 ) <= "110";
				T ( 9 TO 11 ) <= "111";
				T ( 23 TO 24 ) <= "10";
				T ( 29 TO 30 ) <= "01";
				T ( 35 TO 35 ) <= "1";
			WHEN S1 =>
				T(18) <= '1';
				T(19) <= '1';
				T ( 23 TO 24 ) <= "10";
				T ( 29 TO 30 ) <= "01";
				T ( 31 TO 31 ) <= "1";
				T ( 32 TO 32 ) <= "1";
			WHEN S2 =>
				T(20) <= '1';
				T(21) <= '1';
				T(22) <= '1';
				T ( 0 TO 2 ) <= "100";
				T ( 3 TO 5 ) <= "101";
				T ( 23 TO 24 ) <= "11";
				T ( 25 TO 26 ) <= "01";
				T ( 27 TO 28 ) <= "10";
				T ( 29 TO 30 ) <= "10";
				T ( 31 TO 31 ) <= "1";
				T ( 32 TO 32 ) <= "1";
				T ( 33 TO 33 ) <= "1";
				T ( 34 TO 34 ) <= "1";
				T ( 36 TO 36 ) <= "1";
			WHEN S3 =>
				T(16) <= '1';
				T(17) <= '1';
				T ( 3 TO 5 ) <= "111";
				T ( 25 TO 26 ) <= "10";
				T ( 27 TO 28 ) <= "01";
				T ( 33 TO 33 ) <= "1";
				T ( 34 TO 34 ) <= "1";
			WHEN S4 =>
				T(21) <= '1';
				T ( 25 TO 26 ) <= "10";
			WHEN S5 =>
				T(20) <= '1';
				T ( 0 TO 2 ) <= "110";
				T ( 23 TO 24 ) <= "01";
				T ( 25 TO 26 ) <= "01";
			WHEN done => complete <= '1';
		END CASE;
	END PROCESS;

END ARCHITECTURE;